name: super_custom_bars
description: A Super Custom Bar library
version: 1.0.0
# homepage: https://github.com/otocampos/SuperCustomBar

environment:
  sdk: '>=2.15.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2


    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.



dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
